### ISSUE TITLE
Missing function farthest_point_sample

### ISSUE THREAD

**Issue by BSharmi** [smiles724/VQMAE#1]
Hi there!
Great work! Would you please point me to `farthest_point_sample` function? I see it is used in surfformer_v1.py but not defined anywhere else. Did I miss something?

Thank you!!

**Comment by smiles724** [comment]
Hi, dear Sharmi, thanks for your interest in our work and thorough investigation of the code. 

The SurfFormer V1 has been abandoned, so I deleted some unnecessary functions. Apologize for the confusion.
The original code of  `farthest_point_sample ` is written as below:
```
def farthest_point_sample(xyz, npoint, mask):
    """
    https://github.com/CGuangyan-BIT/PointGPT/blob/9c56432a7b7dc4a071ef681f3ca6cd0f7babba0f/segmentation/pointnet_util.py
    Input:
        xyz: pointcloud data, [B, N, 3]
        npoint: number of samples
        mask: [B, N]
    Return:
        patches: sampled pointcloud index, [B, npoint]
    """
    device = xyz.device
    B, N, C = xyz.shape
    patches = torch.zeros(B, npoint, dtype=torch.long).to(device)
    distance = torch.ones(B, N).to(device) * 1e10
    weights = torch.ones_like(mask).float() * mask
    farthest = torch.multinomial(weights / torch.sum(weights, dim=-1, keepdim=True), num_samples=1).squeeze(-1).to(device)
    batch_indices = torch.arange(B, dtype=torch.long).to(device)
    for i in range(npoint):
        patches[:, i] = farthest
        patch = xyz[batch_indices, farthest, :].view(B, 1, 3)
        dist = torch.sum((xyz - patch) ** 2, -1)
        dist[~mask] = 1e-10
        distance = torch.min(distance, dist)
        farthest = torch.max(distance, -1)[1]
    return patches
```
which was modified from the `PointGPT` paper. However, it requires a specific number of points, i.e., `npoint`, which is not optimal for processing protein surfaces. As you know, the size varies significantly from protein to protein. Some may have tens of thousands of surface points while others may merely have hundreds of surface points. 

To alleviate the problem, we adopt `torch_geometric.nn.fps` API in SurfFormer V2 to downsample the surface point cloud. It allows us to sample points with a ratio instead of a fixed number. I hope this can resolve your question.
